### ISSUE TITLE
can I use in XPS9570 8300H

### ISSUE THREAD

**Issue by wanghuu** [bavariancake/XPS9570-macOS#12]
My laptop is XPS 9579 I5 8300H could i use this?

**Comment by bavariancake** [comment]
Many (maybe most?) problems solved by this repo are going to apply to your system, but there may be differences. It's certainly a path worth pursuing, and I encourage you to do that, then submit pull requests with changes we can all benefit from. Be the change you want to see in the world 🧚‍♂️

Asking someone else if this will work for you is really asking them to do all of this work for you. If you don't want to do it, that's fine - nobody has an issue with that. The solution is to go to an Apple store and buy a MacBook. Before you retort that you could buy a ton of actual apples for the price of a MacBook, consider that money is really a stored form of labor, which I conjecture you're avoiding by asking if this repo will work for your particular system.

**Comment by bavariancake** [comment]
I apologize if this sounds rude, because I don't mean to be. I'm hoping people will spend more time testing things, finding solutions, and adding to the shared knowledge around hackintoshes that we all benefit from. 99% of what I do is just to compile what others have done into a config you can use for a single system - without their contributions, none of this would work.

**Comment by bavariancake** [comment]
Most issues will probably be similar, and this would be a good starting point. However, you will have to do that work yourself.
