### ISSUE TITLE
BIOS update 1.13.0

### ISSUE THREAD

**Issue by romton843** [bavariancake/XPS9570-macOS#40]
Hi everybody,
As some of you might have seen, a new BIOS update is available.
Simple question, can we update without changing anything or does it need some modification in the config.plist ?

**Comment by erenatas** [comment]
It shouldn't be a problem. But you can wait for someone to test it too. Or you can too :)

**Comment by romton843** [comment]
I tried and everything seems to be working. Thanks.

**Comment by bavariancake** [comment]
I update the tested BIOS version in the readme (although you beat me to it!). If there aren't any notes in the change history about problems, it should be safe to update without changes.

If you test something and find that something works but hasn't been mentioned yet, a pull request is always appreciated :)

**Comment by attilagyorffy** [comment]
I'm just wondering... How does one upgrade the BIOS on the XPS 9570 if they only have macOS installed and no Windows? Thanks in advance.

**Comment by attilagyorffy** [comment]
Actually I should have googled before I asked. I'm surprised how much work has been done in the architecture side of things on PCs in the last few years. Turns out you can just format a USB drive, drop in the latest BIOS downloaded from the Dell site, (the .exe file), reboot the system and select the boot options using F12 and the BIOS upgrade feature is right there thanks to UEFI and Intel's ME FW tool. It was super simple. I'm shocked and clearly haven't been using PCs for at least a decade. :) I'm running BIOS 1.13.0 successfully and macOS has booted and runs just fine without any issues. <3
