### ISSUE TITLE
Swap BrcmFirmwareRepo.kext for BrcmFirmwareData.kext

### ISSUE THREAD

**Issue by 49616e** [bavariancake/XPS9570-macOS#51]
Is there a particular reason BrcmFirmwareData.kext is not being used here? I'm using BrcmBluetoothInjector.kext + BrcmFirmwareData.kext + BrcmPatchRAM3.kext with a DW1830 and BT works perfectly fine without touching /L/E.

**Comment by bavariancake** [comment]
I install my kexts into `CLOVER/kexts/Other` as well as `/Library/Extensions`, and that requires BrcmFirmwareRepo, so that's really the only reason.

Does BrcmFirmwareData load the Bluetooth firmware as well (should be something like `Version: 6.0.14d3 (v5 c4518)`)?

I've read 100 different things about where and how to inject your kexts, most of them conflicting, so I wouldn't take my approach as the "correct" one, but I haven't seen any kext-loading problem this way.

It would be convenient to do everything via Clover injection only. Is that what you're doing? Have you had any issues with it?

**Comment by 49616e** [comment]
As far as I know, both `BrcmFirmwareData` and `BrcmFirmwareRepo` are only "firmware repos", the only difference is that one can be injected via Clover and the other has to be installed to /L/E. `BrcmPatchRAM*` kexts contain the actual fw uploader. `BrcmBluetoothInjector` contains a fix for Catalina but also works with Mojave, so there's no reason not to use this new combination instead. 

I'm able to inject the aforementioned BrcmBluetoothInjector.kext + BrcmFirmwareData.kext + BrcmPatchRAM3.kext combination (acquired from [here](https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?page=6&tab=comments#comment-2693219) ) via Clover and I'm seeing no BT issues at the moment. Magic Trackpad 2 works perfectly fine and the fw version I'm seeing is `v5 c4510`. 

However, sleep still doesn't work on my machine yet so I can't test if it works after waking up the computer, but I think it would work just fine.

**Comment by calbear92** [comment]
I had some issues with the Catalina update where it killed off my BT. I installed the 3 BT related kexts injected via Clover only and I got the BT NOT available.

I put the BrcmFirmwareRepo and BrcmPatchRam3 kexts into the L/E folder and it worked normally.

However, I updated to Clover 5098 and the latest kexts: AirportBcrmFixup, AppleALC, Lilu, VirtualSMC, WhateverGreen  and then got the BT NOT available. Since I didn't see any notes about this, I used Time Machine to restore before the updates. Still didn't work!

I redownloaded Bavariancake's EFI (Mahalo for all you and everyone's help) and then, BT worked. Cautiously, updated to latest Catalina update. BT still working.

Cautiously, updated to Clover 5098, BT still working.

I'm not going to mess around with the other kext updates since that's what killed off my BT until I see that others have had successful updates.

#IfAintBrokeDontFixIt #WhenWillILearn

**Comment by calbear92** [comment]
I guess I couldn't leave well-enough alone- it's the updated Lilu kext that breaks BT: stay on version 1.3.8. The latest version 1.3.9 breaks it. The other updated kexts work just fine.

**Comment by calbear92** [comment]
curiously, my BT v5 4518, but DISCOVERABLE: NO.

Any ideas on how to fix this?

**Comment by calbear92** [comment]
My Catalina Hackintosh was beginning to run so sluggish that I bit the bullet and went back to Mojave.

My latest stable BT: C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareRepo 2.3.0d3 + L/E: BrcmFirmwareRepo 2.3.0d3, BrcmPatchRam3 2.3.0d3.

I tried various combinations and none of them worked:

C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareData 2.5, L/E: none: no BT

C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareRepo 2.3.0d3; L/E none: no BT

C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareData 2.5, L/E: BrcmPatchRam3 2.5, BrcmFirmwareData 2.5: no BT

C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareData 2.3.0d3, L/E: BrcmPatchRam3 2.5, BrcmFirmwareData 2.5: no BT


C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareData 2.3.0d3, L/E: BrcmPatchRam3 2.3,0d3, BrcmFirmwareData 2.3.0d3: no BT

C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareRepo 2.3.0d3; L/E BrcmPatchRam3 2.5, BrcmFirmwareData 2.5: no BT

**Comment by calbear92** [comment]
Another successful combination: C/K/O: BrcmBluetoothInjector 2.5, BrcmPatchRam3 2.5, BrcmFirmwareData 2.5 + L/E: BrcmFirmwareRepo 2.3.0d3, BrcmPatchRam3 2.3.0d3

**Comment by bavariancake** [comment]
Switched from BrcmFirmwareRepo.kext -> BrcmFirmwareData.kext in commit 
b9b383c4240329ca5ade4613d6dbbec3ce453c21. Tested for a week or so and no issues on Catalina. I'm now running all my kexts from Clover only.

I did notice that VoodooI2C has issues loading from Clover on Mojave, but that's unrelated to Bluetooth.

I also noticed that with Catalina, you may get intermittent issues while making changes to Bluetooth kexts, but oddly those disappear after a few boots and settling on a set of kexts. This makes testing difficult, and I suspect @calbear92 was running into this quirk.
