### ISSUE TITLE
Placement of kexts EFI or /Library/Extensions?

### ISSUE THREAD

**Issue by attilagyorffy** [bavariancake/XPS9570-macOS#52]
Hi there,

First of all, thank you for the amazing support on Dell XPS 9570. I am hoping to be able to contribute to your repository as soon as possible but I'm just scratching the surface of this thing yet.

I have been doing some research regarding the placement of kexts and whilst I understand the basics, it does not seem to be entirely clear where you'd place the kexts listed in this repository.

I've got all of these currently sitting in the `EFI/Clover/kexts/Other` directory in order to ensure boting but it just doesn't feel like the right thing to do. Whilst I understand that some of these are necessarily placed in the EFI partition in order to boot, from the repository it doesn't seem to be clear what should go where. According to tonymacx86, the placement of all kexts in `EFI/Clover/kexts/Other` is wrong and some should be put into the system partition under `/Library/Extensions`:

> It is a mistake to install everything to Clover/kexts. Contrary to popular hackintosh myth, it does not result in a cleaner install (the opposite is true). Many kexts will not work from Clover/kexts, so installing them to /S/L/E where they can be included in kernel cache is the best approach.

As stated in [this guide](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/).

Can someone please explain this in a little more detail?

Thanks in advance.

**Comment by jaromeyer** [comment]
Hi @attilagyorffy,

I know this probably is too late, but I'm going to write this anyway. You should install all the .kext into /L/E  with for example Hackintool. If clover detects either FakeSMC or VirtualSMC it won't inject any of the kexts in EFI/Clover/kexts/Other. This is because one of those kexts is required to get a Hackintosh working, so if one is present in /L/E clover assumes that you have installed everything to /L/E and injection isn't required. Tho you should still keep the most basic kexts (FakeSMC/VirtualSMC, Lilu, Whatevergreen, VoodooI2C and PS2) in EFI/Clover/kexts/Other so you can boot up the installer or recovery.
