### ISSUE TITLE
Intel UHD Graphics 630 1536: previously 2048MB

### ISSUE THREAD

**Issue by calbear92** [bavariancake/XPS9570-macOS#55]
My previously iterations had Intel UHD Graphics 630 2048mb, but after the latest updates to Catalina and BT disaster, I'm noticing that there's only 1536mb.

Not sure what practical performance gains might be there, but anyone have experience in getting that 500 mg back (and still have everything else work)?

I'm relatively happy with the current state of things- I've broken it too many times tinkering with EFI. lol

**Comment by calbear92** [comment]
I guess I couldn't leave well-enough alone- it's the updated Lilu kext that breaks BT: stay on version 1.3.8. The latest version 1.3.9 breaks it.

**Comment by khoa-nv** [comment]
I got a same problem with you. I tried to set `ig-platform-id ` to `0x3e9b0000` and it work properly.

**Comment by bavariancake** [comment]
Unless you can measure a performance difference between 1536MB and 2048MB VRAM, I recommend you stick with the defaults. I found no difference myself.

We're on Lilu 1.4.1 with working Bluetooth/Wifi on Catalina and Mojave now, in case anyone suspects the Lilu version to be a problem.

Closing issue for now since I'm not sure there's a benefit to be gained by switching to 2048MB. If you notice that there is a difference, we can reopen the issue.
