### ISSUE TITLE
The Caps Lock LED does not light up (but caps lock works)

### ISSUE THREAD

**Issue by gfab-io** [bavariancake/XPS9570-macOS#64]
Hi there, I have an annoying problem regarding the capital lock key: the LED does not light up ... when I press the key it flashes but goes off immediately. Anyway the capital lock works.
My laptop XPS 9570, i7 8750H, 1920x1080, 8GB RAM, 500GB SSD (WD SN750)

**Comment by romton843** [comment]
Same for me...

**Comment by gfab-io** [comment]
I had updated Clover and all the kexts to the latest version: I solved this problem by removing the latest versions of VoodooI2C.kext, VoodooI2CHID.kext and VoodooPS2Controller.kext ... basically I put back the original versions of the EFI.
Honestly, I have not yet had the opportunity to verify which of the three kexts is responsible, or if all three are responsible.
(My keyboard has Italian layout).

**Comment by bavariancake** [comment]
Which VoodooPS2Controller were you having problems with @gfab-io? Was it https://github.com/acidanthera/VoodooPS2 by any chance?

**Comment by bavariancake** [comment]
Anyway, I ran into similar keyboard (and trackpad) issues when I was trying VoodooPS2. I have a US/English keyboard, so the layout is probably not at fault.

Since it sounds like VoodooPS2 was causing problems for you as well, I'm gonna close this issue as resolved. Feel free to comment if the original kexts didn't resolve everything, and I'll re-open it.
