### ISSUE TITLE
Using BIOS > 1.11.2, Internal Display is not working when connected to External Display via USB-C(TB) 

### ISSUE THREAD

**Issue by duongle26** [bavariancake/XPS9570-macOS#65]
The issue is that OS detects the display, the external display lights up but the internal display is blackout. 
**This only happens when using BIOS > 1.11.2**
![Untitled](https://user-images.githubusercontent.com/28813618/74045933-39e53700-4a00-11ea-980b-62405d67ffcf.jpg)

**Comment by bavariancake** [comment]
I see the latest BIOS for the 9570 is [1.15.0](https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=gxff7&oscode=wt64a&productcode=xps-15-9570-laptop) - what is 11.2?

When you close the lid, both external displays should stay on. Wait a few seconds, and open the lid again. Does the internal LCD power up then?

Nice setup btw.

**Comment by duongle26** [comment]
@bavariancake Sorry I mean 1.11.2.
seems like I encounter the same problem as #60 .

**Comment by duongle26** [comment]
The internal LCD is not working since reaching the Apple Loading Screen when booting up. I connect my XPS with external screens via thunderbolt port.

**Comment by bavariancake** [comment]
#60 was using this repo for a 9560, so probably unrelated.

What happens when you close the lid? Do both displays keep working?

What happens when you re-open the lid after a few seconds?

If you do not connect any external monitors and boot, does the internal LCD work?

If that works, what happens when you connect one DisplayPort display after logging in (fully booted)? What about both of your DP displays?

**Comment by duongle26** [comment]
@bavariancake surprisingly, this issue was solved by closing and reopening the lid, then all displays should work.
And to follow your question:
1. What happens when you close the lid? Do both displays keep working?
-> Yeah, external displays keep working

2. What happens when you re-open the lid after a few seconds?
-> It is at this moment the problem was solved, the internal display, as well as external displays, light up as normal

3. If you do not connect any external monitors and boot, does the internal LCD work?
-> Yes

4. If that works, what happens when you connect one DisplayPort display after logging in (fully booted)? What about both of your DP displays?
-> The external displays work but the internal display does not

I can see this is a temporary solution to this problem, but it is too inconvenient to close and reopen the lid whenever booting up the machine to get all the display work.
I hope these pieces of information are useful to you.

**Comment by duongleh** [comment]
Found a simplier solution: after fully booted, put the laptop to sleep and wake it up, then it works !

**Comment by bavariancake** [comment]
I've been debugging WhateverGreen to see if I can fix this problem permanently (since I have the same issue), but haven't gotten it to work yet. Interestingly, I can see how the framebuffers are initialized differently when it works (resume from sleep or clamshell open) and when it doesn't.

 I'll let you know when I have something. Might be a little while.

**Comment by OldDream** [comment]
Thank U, I use a typeC to HDMI hub and got the same problem, I have 4k screen, hibernation and wake up light up the screen， but make it flick...
Solved by down grade from 1.17 to 1.12 .

**Comment by OldDream** [comment]
It seems this problem has been fixed since I upgrade all kext to the latest, weg,lilu,opencore......etc,now it works well with BIOS 1.17.1
